apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dashboards-deployment.yaml
  - dashboards-ingress.yaml
  - dashboards-service.yaml
  - service.yaml
  - statefulset.yaml
