apiVersion: v1
kind: Service
metadata:
  name: opensearch
  labels:
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/part-of: nyambot
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: opensearch
  ports:
    - name: http
      port: 9200
      targetPort: http
    - name: performance
      port: 9600
      targetPort: performance
