apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nyambot-backend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http01
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - nyambot.n-e.kr
      secretName: nyambot-backend-tls
  rules:
    - host: nyambot.n-e.kr
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: nyambot-backend
                port:
                  name: http
          - path: /health
            pathType: Exact
            backend:
              service:
                name: nyambot-backend
                port:
                  name: http
