apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nyambot-prod
resources:
  - ../../base
  - ingress.yaml
images:
  - name: ghcr.io/nyambot/backend
    newTag: c2602e4a80c5c4199cad0f7444a9af7d36cb1c2a
