apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nyambot-prod
resources:
  - ../../base
  - ingress.yaml
images:
  - name: ghcr.io/nyambot/backend
    newTag: 4445cc2e118d3f9a25452dc63bcd7782b275243d
