apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nyambot-prod
resources:
  - ../../base
  - ingress.yaml
images:
  - name: ghcr.io/nyambot/backend
    newTag: e11aa2668ef6c3461b7be4a5307ba220c0d69c73
