apiVersion: v1
kind: ConfigMap
metadata:
  name: nyambot-backend-config
data:
  APP_ENV: prod
  API_PREFIX: /api/v1
  FRONTEND_URL: https://nyambot.vercel.app
  CHAT_MESSAGE_BACKEND: opensearch
  OPENSEARCH_URL: http://opensearch:9200
  OPENSEARCH_CHAT_MESSAGES_INDEX: nyambot-chat-messages
  OPENSEARCH_VERIFY_CERTS: "false"
  CHAT_MESSAGE_QUEUE_ENABLED: "true"
  CHAT_MESSAGE_QUEUE_NAME: nyambot-chat-message-save
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  RABBITMQ_VHOST: /
  HUGGINGFACE_RERANK_ENABLED: "true"
